---
.puppet-lint.rc:
  extra_disabled_lint_checks:
    - arrow_on_right_operand_line
.travis.yml:
  beaker_sets:
    - centos7-64
spec/spec_helper.rb:
  custom_facts:
    - name: systemd
      value: true
      source: puppet-systemd
spec/spec_helper_acceptance.rb:
  install_epel: true
