---
.puppet-lint.rc:
  extra_disabled_lint_checks:
    - arrow_on_right_operand_line
spec/spec_helper.rb:
  custom_facts:
    - name: root_home
      value: /root
      source: puppetlabs-stdlib
    - name: systemd
      value: true
      source: puppet-systemd
